import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Sparkles } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { SuggestionCard } from '@/components/charts/suggestion-card';
import { friendlyErrorMessage } from '@/lib/friendly-error';

type Severity = 'info' | 'warn' | 'good';
type Insight = { severity: Severity; text: string };

function normalizeSeverity(value: unknown): Severity {
  return value === 'warn' || value === 'good' ? value : 'info';
}

// On-demand (not auto-loaded) by design — Gemini's free tier is
// rate-limited and shared across every admin/lister using the app, so this
// only calls out when someone explicitly asks for it, backed by a 20s
// per-user cooldown server-side (request_ai_insights_cooldown()).
export function AiInsights({ role, stats }: { role: 'admin' | 'lister'; stats: unknown }) {
  const [insights, setInsights] = useState<Insight[] | null>(null);

  const generate = useMutation({
    mutationFn: async () => {
      const { data, error } = await supabase.functions.invoke('generate-ai-insights', { body: { role, stats } });
      if (error) throw error;
      const raw = (data?.insights ?? []) as { severity: unknown; text: string }[];
      return raw.map((r) => ({ severity: normalizeSeverity(r.severity), text: r.text }));
    },
    onSuccess: setInsights,
  });

  return (
    <div className="mb-5">
      <div className="mb-2 flex items-center justify-between gap-3">
        <h3 className="flex items-center gap-1.5 text-sm font-bold">
          <Sparkles className="h-4 w-4 text-accent" strokeWidth={2.25} /> AI Insights
        </h3>
        <Button size="sm" variant="secondary" disabled={generate.isPending} onClick={() => generate.mutate()}>
          {generate.isPending ? 'Thinking…' : insights ? 'Refresh' : 'Generate AI Insights'}
        </Button>
      </div>

      {generate.isError ? <p className="mb-2 text-xs text-bad">{friendlyErrorMessage(generate.error)}</p> : null}

      {insights && insights.length > 0 ? (
        <div className="flex flex-col gap-2">
          {insights.map((s, i) => (
            <SuggestionCard key={i} severity={s.severity} text={s.text} />
          ))}
        </div>
      ) : insights ? (
        <p className="text-xs text-muted">No notable insights from the current data.</p>
      ) : (
        <p className="text-xs text-muted">
          Get a quick natural-language summary of the numbers below, generated by AI.
        </p>
      )}
    </div>
  );
}
